// This file is generated by scripts/generate-data.js.
// Do not edit it manually. Edit content.config.js or the Markdown files instead.

const reviewData = [
  {
    "category": "开始使用",
    "sections": [
      {
        "id": "welcome",
        "title": "欢迎页",
        "file": "content/welcome.md",
        "topics": [
          {
            "id": "welcome-start",
            "title": "开始使用",
            "file": "content/welcome.md",
            "articles": [
              {
                "id": "welcome",
                "title": "欢迎来到你的知识库",
                "file": "content/welcome.md"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "category": "测试方向",
    "sections": [
      {
        "id": "test-direction-test-basic",
        "title": "测试基础",
        "file": "content/test-direction/test-basic/index.md",
        "topics": [
          {
            "id": "test-direction-test-basic-concepts",
            "title": "测试基础中的核心概念",
            "file": "content/test-direction/test-basic/concepts/index.md",
            "articles": [
              {
                "id": "test-direction-test-basic-concepts-smoke-test",
                "title": "冒烟测试",
                "file": "content/test-direction/test-basic/concepts/smoke-test.md"
              },
              {
                "id": "test-direction-test-basic-concepts-regression-test",
                "title": "回归测试",
                "file": "content/test-direction/test-basic/concepts/regression-test.md"
              },
              {
                "id": "test-direction-test-basic-concepts-test-case",
                "title": "测试用例",
                "file": "content/test-direction/test-basic/concepts/test-case.md"
              }
            ]
          }
        ]
      },
      {
        "id": "test-direction-api-test",
        "title": "接口测试",
        "file": "content/test-direction/api-test/index.md",
        "topics": [
          {
            "id": "test-direction-api-test-basic-cognition",
            "title": "接口测试中的基础认知",
            "file": "content/test-direction/api-test/basic-cognition/index.md",
            "articles": [
              {
                "id": "test-direction-api-test-basic-cognition-api-testing-overview",
                "title": "接口测试概述",
                "file": "content/test-direction/api-test/basic-cognition/api-testing-overview.md"
              },
              {
                "id": "test-direction-api-test-basic-cognition-api-testing-process",
                "title": "接口测试流程",
                "file": "content/test-direction/api-test/basic-cognition/api-testing-process.md"
              },
              {
                "id": "test-direction-api-test-basic-cognition-api-testing-case-design",
                "title": "接口测试用例设计",
                "file": "content/test-direction/api-test/basic-cognition/api-testing-case-design.md"
              },
              {
                "id": "test-direction-api-test-basic-cognition-api-doc-review-and-test-point-extraction",
                "title": "接口文档评审与测试点提炼",
                "file": "content/test-direction/api-test/basic-cognition/api-doc-review-and-test-point-extraction.md"
              },
              {
                "id": "test-direction-api-test-basic-cognition-preconditions-test-data-and-dependency-mapping",
                "title": "前置条件、测试数据与依赖识别",
                "file": "content/test-direction/api-test/basic-cognition/preconditions-test-data-and-dependency-mapping.md"
              }
            ]
          },
          {
            "id": "test-direction-api-test-validation-and-consistency",
            "title": "结果验证与一致性",
            "file": "content/test-direction/api-test/validation-and-consistency/index.md",
            "articles": [
              {
                "id": "test-direction-api-test-validation-and-consistency-response-contract-vs-business-result",
                "title": "响应契约和业务结果为什么要分开看",
                "file": "content/test-direction/api-test/validation-and-consistency/response-contract-vs-business-result.md"
              },
              {
                "id": "test-direction-api-test-validation-and-consistency-business-key-and-state-checks",
                "title": "业务键、状态机与结果校验怎么配合",
                "file": "content/test-direction/api-test/validation-and-consistency/business-key-and-state-checks.md"
              },
              {
                "id": "test-direction-api-test-validation-and-consistency-async-side-effect-verification",
                "title": "异步副作用与最终一致性怎么验",
                "file": "content/test-direction/api-test/validation-and-consistency/async-side-effect-verification.md"
              },
              {
                "id": "test-direction-api-test-validation-and-consistency-cache-db-read-after-write-and-lag",
                "title": "缓存、数据库与读后写一致性",
                "file": "content/test-direction/api-test/validation-and-consistency/cache-db-read-after-write-and-lag.md"
              },
              {
                "id": "test-direction-api-test-validation-and-consistency-message-dedup-compensation-and-eventual-consistency",
                "title": "消息去重、补偿与最终一致性",
                "file": "content/test-direction/api-test/validation-and-consistency/message-dedup-compensation-and-eventual-consistency.md"
              }
            ]
          },
          {
            "id": "test-direction-api-test-risk-and-control",
            "title": "异常、权限与风险控制",
            "file": "content/test-direction/api-test/risk-and-control/index.md",
            "articles": [
              {
                "id": "test-direction-api-test-risk-and-control-error-inputs-and-risk-defense",
                "title": "异常输入与风险防线怎么设计",
                "file": "content/test-direction/api-test/risk-and-control/error-inputs-and-risk-defense.md"
              },
              {
                "id": "test-direction-api-test-risk-and-control-permission-model-and-cross-role-testing",
                "title": "权限模型与跨角色测试怎么落",
                "file": "content/test-direction/api-test/risk-and-control/permission-model-and-cross-role-testing.md"
              },
              {
                "id": "test-direction-api-test-risk-and-control-rate-limit-replay-and-abuse-protection",
                "title": "限流、重放与滥用防护测试",
                "file": "content/test-direction/api-test/risk-and-control/rate-limit-replay-and-abuse-protection.md"
              },
              {
                "id": "test-direction-api-test-risk-and-control-sensitive-data-desensitization-and-audit",
                "title": "敏感数据、脱敏与审计线索",
                "file": "content/test-direction/api-test/risk-and-control/sensitive-data-desensitization-and-audit.md"
              },
              {
                "id": "test-direction-api-test-risk-and-control-batch-operation-compensation-and-write-risk",
                "title": "批量操作、补偿与高风险写接口",
                "file": "content/test-direction/api-test/risk-and-control/batch-operation-compensation-and-write-risk.md"
              }
            ]
          },
          {
            "id": "test-direction-api-test-stability-and-performance",
            "title": "稳定性与性能保障",
            "file": "content/test-direction/api-test/stability-and-performance/index.md",
            "articles": [
              {
                "id": "test-direction-api-test-stability-and-performance-reliability-vs-throughput",
                "title": "可靠性、吞吐与延迟为什么要一起看",
                "file": "content/test-direction/api-test/stability-and-performance/reliability-vs-throughput.md"
              },
              {
                "id": "test-direction-api-test-stability-and-performance-capacity-ramp-and-failure-thresholds",
                "title": "容量爬坡与失效阈值如何判断",
                "file": "content/test-direction/api-test/stability-and-performance/capacity-ramp-and-failure-thresholds.md"
              },
              {
                "id": "test-direction-api-test-stability-and-performance-dependency-timeout-and-circuit-breaker-testing",
                "title": "依赖超时与熔断降级测试",
                "file": "content/test-direction/api-test/stability-and-performance/dependency-timeout-and-circuit-breaker-testing.md"
              }
            ]
          },
          {
            "id": "test-direction-api-test-engineering-practice",
            "title": "调试、自动化与测试输出",
            "file": "content/test-direction/api-test/engineering-practice/index.md",
            "articles": [
              {
                "id": "test-direction-api-test-engineering-practice-debugging-to-regression-closure",
                "title": "从联调定位到回归闭环怎么串起来",
                "file": "content/test-direction/api-test/engineering-practice/debugging-to-regression-closure.md"
              },
              {
                "id": "test-direction-api-test-engineering-practice-test-data-and-environment-governance",
                "title": "测试数据与环境治理为什么会影响接口质量",
                "file": "content/test-direction/api-test/engineering-practice/test-data-and-environment-governance.md"
              },
              {
                "id": "test-direction-api-test-engineering-practice-case-layering-and-assertion-strategy",
                "title": "用例分层与断言策略怎么设计",
                "file": "content/test-direction/api-test/engineering-practice/case-layering-and-assertion-strategy.md"
              },
              {
                "id": "test-direction-api-test-engineering-practice-test-account-environment-isolation-and-cleanup",
                "title": "测试账号、环境隔离与清理机制",
                "file": "content/test-direction/api-test/engineering-practice/test-account-environment-isolation-and-cleanup.md"
              },
              {
                "id": "test-direction-api-test-engineering-practice-regression-scope-and-change-impact-analysis",
                "title": "接口回归集与变更影响分析",
                "file": "content/test-direction/api-test/engineering-practice/regression-scope-and-change-impact-analysis.md"
              }
            ]
          },
          {
            "id": "test-direction-api-test-advanced-topics",
            "title": "进阶专题",
            "file": "content/test-direction/api-test/advanced-topics/index.md",
            "articles": [
              {
                "id": "test-direction-api-test-advanced-topics-api-authentication-and-token",
                "title": "鉴权与 Token 机制",
                "file": "content/test-direction/api-test/advanced-topics/api-authentication-and-token.md"
              },
              {
                "id": "test-direction-api-test-advanced-topics-api-status-code-and-error-handling",
                "title": "错误码、状态码与异常处理",
                "file": "content/test-direction/api-test/advanced-topics/api-status-code-and-error-handling.md"
              },
              {
                "id": "test-direction-api-test-advanced-topics-api-testing-interview-questions",
                "title": "接口测试常见面试题",
                "file": "content/test-direction/api-test/advanced-topics/api-testing-interview-questions.md"
              },
              {
                "id": "test-direction-api-test-advanced-topics-api-testing-report",
                "title": "接口测试报告与缺陷记录",
                "file": "content/test-direction/api-test/advanced-topics/api-testing-report.md"
              }
            ]
          },
          {
            "id": "test-direction-api-test-quality-dimensions",
            "title": "核心质量维度",
            "file": "content/test-direction/api-test/quality-dimensions/index.md",
            "articles": [
              {
                "id": "test-direction-api-test-quality-dimensions-api-security-testing",
                "title": "安全性测试（接口视角）",
                "file": "content/test-direction/api-test/quality-dimensions/api-security-testing.md"
              },
              {
                "id": "test-direction-api-test-quality-dimensions-availability-testing",
                "title": "可用性测试",
                "file": "content/test-direction/api-test/quality-dimensions/availability-testing.md"
              },
              {
                "id": "test-direction-api-test-quality-dimensions-compatibility-testing",
                "title": "兼容性测试",
                "file": "content/test-direction/api-test/quality-dimensions/compatibility-testing.md"
              },
              {
                "id": "test-direction-api-test-quality-dimensions-correctness-testing",
                "title": "正确性测试",
                "file": "content/test-direction/api-test/quality-dimensions/correctness-testing.md"
              },
              {
                "id": "test-direction-api-test-quality-dimensions-data-consistency-testing",
                "title": "数据一致性测试",
                "file": "content/test-direction/api-test/quality-dimensions/data-consistency-testing.md"
              },
              {
                "id": "test-direction-api-test-quality-dimensions-idempotency-testing",
                "title": "幂等性测试",
                "file": "content/test-direction/api-test/quality-dimensions/idempotency-testing.md"
              },
              {
                "id": "test-direction-api-test-quality-dimensions-performance-testing",
                "title": "接口性能测试",
                "file": "content/test-direction/api-test/quality-dimensions/performance-testing.md"
              },
              {
                "id": "test-direction-api-test-quality-dimensions-robustness-testing",
                "title": "健壮性测试",
                "file": "content/test-direction/api-test/quality-dimensions/robustness-testing.md"
              },
              {
                "id": "test-direction-api-test-quality-dimensions-stability-testing",
                "title": "稳定性测试",
                "file": "content/test-direction/api-test/quality-dimensions/stability-testing.md"
              }
            ]
          },
          {
            "id": "test-direction-api-test-tools-and-practice",
            "title": "工具与实践",
            "file": "content/test-direction/api-test/tools-and-practice/index.md",
            "articles": [
              {
                "id": "test-direction-api-test-tools-and-practice-api-automation-pytest-requests",
                "title": "pytest + requests 接口自动化",
                "file": "content/test-direction/api-test/tools-and-practice/api-automation-pytest-requests.md"
              },
              {
                "id": "test-direction-api-test-tools-and-practice-api-data-validation",
                "title": "MySQL / Redis 数据校验",
                "file": "content/test-direction/api-test/tools-and-practice/api-data-validation.md"
              },
              {
                "id": "test-direction-api-test-tools-and-practice-api-mock-testing",
                "title": "Mock 在接口测试中的应用",
                "file": "content/test-direction/api-test/tools-and-practice/api-mock-testing.md"
              },
              {
                "id": "test-direction-api-test-tools-and-practice-api-performance-with-jmeter",
                "title": "JMeter 接口性能测试",
                "file": "content/test-direction/api-test/tools-and-practice/api-performance-with-jmeter.md"
              },
              {
                "id": "test-direction-api-test-tools-and-practice-api-tools-postman-apifox",
                "title": "Postman / Apifox 调试",
                "file": "content/test-direction/api-test/tools-and-practice/api-tools-postman-apifox.md"
              }
            ]
          }
        ]
      },
      {
        "id": "test-direction-performance-test",
        "title": "性能测试",
        "file": "content/test-direction/performance-test/index.md",
        "topics": [
          {
            "id": "test-direction-performance-test-basics",
            "title": "性能测试基础",
            "file": "content/test-direction/performance-test/basics/index.md",
            "articles": [
              {
                "id": "test-direction-performance-test-basics-performance-test-types",
                "title": "性能测试、压力测试、容量测试怎么区分",
                "file": "content/test-direction/performance-test/basics/performance-test-types.md"
              },
              {
                "id": "test-direction-performance-test-basics-performance-workload-modeling",
                "title": "性能测试负载模型怎么设计",
                "file": "content/test-direction/performance-test/basics/performance-workload-modeling.md"
              },
              {
                "id": "test-direction-performance-test-basics-business-model-alignment-and-target-definition",
                "title": "性能场景、业务模型与压测目标对齐",
                "file": "content/test-direction/performance-test/basics/business-model-alignment-and-target-definition.md"
              },
              {
                "id": "test-direction-performance-test-basics-warmup-steady-state-and-ramp-design",
                "title": "预热、稳态与收尾阶段怎么设计",
                "file": "content/test-direction/performance-test/basics/warmup-steady-state-and-ramp-design.md"
              },
              {
                "id": "test-direction-performance-test-basics-performance-test-baseline",
                "title": "性能测试为什么必须先建基线",
                "file": "content/test-direction/performance-test/basics/performance-test-baseline.md"
              }
            ]
          },
          {
            "id": "test-direction-performance-test-metrics-and-tooling",
            "title": "性能测试中的指标与工具",
            "file": "content/test-direction/performance-test/metrics-and-tooling/index.md",
            "articles": [
              {
                "id": "test-direction-performance-test-metrics-and-tooling-performance-observability-and-evidence",
                "title": "性能监控、埋点与证据链怎么建",
                "file": "content/test-direction/performance-test/metrics-and-tooling/performance-observability-and-evidence.md"
              },
              {
                "id": "test-direction-performance-test-metrics-and-tooling-client-server-metric-alignment",
                "title": "客户端和服务端指标怎么对齐看",
                "file": "content/test-direction/performance-test/metrics-and-tooling/client-server-metric-alignment.md"
              },
              {
                "id": "test-direction-performance-test-metrics-and-tooling-throughput-percentile-and-error-budget",
                "title": "吞吐、分位值与错误预算",
                "file": "content/test-direction/performance-test/metrics-and-tooling/throughput-percentile-and-error-budget.md"
              },
              {
                "id": "test-direction-performance-test-metrics-and-tooling-logs-metrics-traces-and-evidence-correlation",
                "title": "日志、指标、Trace 怎么对齐证据链",
                "file": "content/test-direction/performance-test/metrics-and-tooling/logs-metrics-traces-and-evidence-correlation.md"
              },
              {
                "id": "test-direction-performance-test-metrics-and-tooling-ue-performance-metrics-and-tooling",
                "title": "性能测试关注指标与工具",
                "file": "content/test-direction/performance-test/metrics-and-tooling/ue-performance-metrics-and-tooling.md"
              }
            ]
          },
          {
            "id": "test-direction-performance-test-analysis-and-location",
            "title": "分析与瓶颈定位",
            "file": "content/test-direction/performance-test/analysis-and-location/index.md",
            "articles": [
              {
                "id": "test-direction-performance-test-analysis-and-location-performance-metrics-interpretation",
                "title": "性能指标应该怎样解读",
                "file": "content/test-direction/performance-test/analysis-and-location/performance-metrics-interpretation.md"
              },
              {
                "id": "test-direction-performance-test-analysis-and-location-capacity-knee-and-breakpoint-detection",
                "title": "压测拐点与容量边界怎么识别",
                "file": "content/test-direction/performance-test/analysis-and-location/capacity-knee-and-breakpoint-detection.md"
              },
              {
                "id": "test-direction-performance-test-analysis-and-location-ab-comparison-single-variable-and-attribution",
                "title": "A/B 对照、单变量实验与归因",
                "file": "content/test-direction/performance-test/analysis-and-location/ab-comparison-single-variable-and-attribution.md"
              },
              {
                "id": "test-direction-performance-test-analysis-and-location-bottleneck-hypothesis-and-verification",
                "title": "瓶颈假设与验证实验怎么做",
                "file": "content/test-direction/performance-test/analysis-and-location/bottleneck-hypothesis-and-verification.md"
              },
              {
                "id": "test-direction-performance-test-analysis-and-location-performance-bottleneck-location",
                "title": "性能瓶颈如何分层定位",
                "file": "content/test-direction/performance-test/analysis-and-location/performance-bottleneck-location.md"
              }
            ]
          },
          {
            "id": "test-direction-performance-test-client-and-server",
            "title": "客户端与服务端性能",
            "file": "content/test-direction/performance-test/client-and-server/index.md",
            "articles": [
              {
                "id": "test-direction-performance-test-client-and-server-client-performance-thinking",
                "title": "客户端性能测试在关注什么",
                "file": "content/test-direction/performance-test/client-and-server/client-performance-thinking.md"
              },
              {
                "id": "test-direction-performance-test-client-and-server-load-generator-and-service-side-bias",
                "title": "压测机瓶颈与服务端瓶颈怎么区分",
                "file": "content/test-direction/performance-test/client-and-server/load-generator-and-service-side-bias.md"
              },
              {
                "id": "test-direction-performance-test-client-and-server-mobile-thermal-memory-pressure-and-throttling",
                "title": "移动端发热、内存压力与降频",
                "file": "content/test-direction/performance-test/client-and-server/mobile-thermal-memory-pressure-and-throttling.md"
              },
              {
                "id": "test-direction-performance-test-client-and-server-dependency-resource-isolation-and-capacity-illusion",
                "title": "下游依赖、资源隔离与容量错觉",
                "file": "content/test-direction/performance-test/client-and-server/dependency-resource-isolation-and-capacity-illusion.md"
              },
              {
                "id": "test-direction-performance-test-client-and-server-server-performance-thinking",
                "title": "服务端性能测试在关注什么",
                "file": "content/test-direction/performance-test/client-and-server/server-performance-thinking.md"
              }
            ]
          }
        ]
      },
      {
        "id": "test-direction-compatibility-test",
        "title": "兼容性测试",
        "file": "content/test-direction/compatibility-test/index.md",
        "topics": [
          {
            "id": "test-direction-compatibility-test-environment-matrix",
            "title": "环境维度与风险矩阵",
            "file": "content/test-direction/compatibility-test/environment-matrix/index.md",
            "articles": [
              {
                "id": "test-direction-compatibility-test-environment-matrix-compatibility-dimensions",
                "title": "兼容性维度怎么拆",
                "file": "content/test-direction/compatibility-test/environment-matrix/compatibility-dimensions.md"
              },
              {
                "id": "test-direction-compatibility-test-environment-matrix-device-fragmentation-and-version-strategy",
                "title": "设备碎片化与版本策略怎么定",
                "file": "content/test-direction/compatibility-test/environment-matrix/device-fragmentation-and-version-strategy.md"
              },
              {
                "id": "test-direction-compatibility-test-environment-matrix-system-webview-and-sdk-compatibility",
                "title": "系统组件、WebView 与 SDK 兼容",
                "file": "content/test-direction/compatibility-test/environment-matrix/system-webview-and-sdk-compatibility.md"
              },
              {
                "id": "test-direction-compatibility-test-environment-matrix-compatibility-priority",
                "title": "兼容性范围如何定优先级",
                "file": "content/test-direction/compatibility-test/environment-matrix/compatibility-priority.md"
              }
            ]
          },
          {
            "id": "test-direction-compatibility-test-design-and-location",
            "title": "用例设计与问题定位",
            "file": "content/test-direction/compatibility-test/design-and-location/index.md",
            "articles": [
              {
                "id": "test-direction-compatibility-test-design-and-location-compatibility-case-design",
                "title": "兼容性用例如何设计",
                "file": "content/test-direction/compatibility-test/design-and-location/compatibility-case-design.md"
              },
              {
                "id": "test-direction-compatibility-test-design-and-location-compatibility-evidence-and-regression-matrix",
                "title": "兼容性证据收集与回归矩阵",
                "file": "content/test-direction/compatibility-test/design-and-location/compatibility-evidence-and-regression-matrix.md"
              },
              {
                "id": "test-direction-compatibility-test-design-and-location-install-upgrade-rollback-and-data-migration",
                "title": "安装、升级、回退与数据迁移",
                "file": "content/test-direction/compatibility-test/design-and-location/install-upgrade-rollback-and-data-migration.md"
              },
              {
                "id": "test-direction-compatibility-test-design-and-location-compatibility-problem-location",
                "title": "兼容性问题如何定位",
                "file": "content/test-direction/compatibility-test/design-and-location/compatibility-problem-location.md"
              }
            ]
          }
        ]
      },
      {
        "id": "test-direction-weak-network-test",
        "title": "弱网测试",
        "file": "content/test-direction/weak-network-test/index.md",
        "topics": [
          {
            "id": "test-direction-weak-network-test-network-fault-models",
            "title": "网络异常模型",
            "file": "content/test-direction/weak-network-test/network-fault-models/index.md",
            "articles": [
              {
                "id": "test-direction-weak-network-test-network-fault-models-latency-loss-jitter",
                "title": "延迟、丢包、抖动与限速",
                "file": "content/test-direction/weak-network-test/network-fault-models/latency-loss-jitter.md"
              },
              {
                "id": "test-direction-weak-network-test-network-fault-models-bandwidth-fluctuation-and-burst-loss",
                "title": "带宽波动与突发丢包场景",
                "file": "content/test-direction/weak-network-test/network-fault-models/bandwidth-fluctuation-and-burst-loss.md"
              },
              {
                "id": "test-direction-weak-network-test-network-fault-models-request-reordering-and-stale-response",
                "title": "乱序、重复响应与过期数据覆盖",
                "file": "content/test-direction/weak-network-test/network-fault-models/request-reordering-and-stale-response.md"
              },
              {
                "id": "test-direction-weak-network-test-network-fault-models-disconnect-switching",
                "title": "断网、切网与重连场景",
                "file": "content/test-direction/weak-network-test/network-fault-models/disconnect-switching.md"
              }
            ]
          },
          {
            "id": "test-direction-weak-network-test-recovery-and-consistency",
            "title": "恢复策略与数据一致性",
            "file": "content/test-direction/weak-network-test/recovery-and-consistency/index.md",
            "articles": [
              {
                "id": "test-direction-weak-network-test-recovery-and-consistency-weak-network-retry-and-idempotency",
                "title": "重试、幂等与重复提交",
                "file": "content/test-direction/weak-network-test/recovery-and-consistency/weak-network-retry-and-idempotency.md"
              },
              {
                "id": "test-direction-weak-network-test-recovery-and-consistency-offline-cache-and-resume-strategy",
                "title": "离线缓存与恢复后续传策略",
                "file": "content/test-direction/weak-network-test/recovery-and-consistency/offline-cache-and-resume-strategy.md"
              },
              {
                "id": "test-direction-weak-network-test-recovery-and-consistency-upload-download-resume-and-checkpoint",
                "title": "上传下载续传与断点恢复",
                "file": "content/test-direction/weak-network-test/recovery-and-consistency/upload-download-resume-and-checkpoint.md"
              },
              {
                "id": "test-direction-weak-network-test-recovery-and-consistency-weak-network-state-recovery",
                "title": "弱网下的状态恢复与提示设计",
                "file": "content/test-direction/weak-network-test/recovery-and-consistency/weak-network-state-recovery.md"
              }
            ]
          }
        ]
      },
      {
        "id": "test-direction-test-tools",
        "title": "测试工具",
        "file": "content/test-direction/test-tools/index.md",
        "topics": [
          {
            "id": "test-direction-test-tools-visual-automation",
            "title": "视觉自动化",
            "file": "content/test-direction/test-tools/visual-automation/index.md",
            "articles": [
              {
                "id": "test-direction-test-tools-visual-automation-visual-automation-overview",
                "title": "视觉自动化与状态识别技术路线",
                "file": "content/test-direction/test-tools/visual-automation/visual-automation-overview.md"
              },
              {
                "id": "test-direction-test-tools-visual-automation-template-matching",
                "title": "模板匹配技术详解",
                "file": "content/test-direction/test-tools/visual-automation/template-matching.md"
              },
              {
                "id": "test-direction-test-tools-visual-automation-ocr",
                "title": "OCR 技术详解",
                "file": "content/test-direction/test-tools/visual-automation/ocr.md"
              },
              {
                "id": "test-direction-test-tools-visual-automation-object-detection-yolo",
                "title": "YOLO 与目标检测技术详解",
                "file": "content/test-direction/test-tools/visual-automation/object-detection-yolo.md"
              },
              {
                "id": "test-direction-test-tools-visual-automation-background-subtraction",
                "title": "背景减除与轻量视频监控",
                "file": "content/test-direction/test-tools/visual-automation/background-subtraction.md"
              },
              {
                "id": "test-direction-test-tools-visual-automation-internal-state-reading",
                "title": "内部接口读取、状态机与规则引擎",
                "file": "content/test-direction/test-tools/visual-automation/internal-state-reading.md"
              },
              {
                "id": "test-direction-test-tools-visual-automation-multi-signal-fusion-and-fallback",
                "title": "多信号融合与降级策略",
                "file": "content/test-direction/test-tools/visual-automation/multi-signal-fusion-and-fallback.md"
              },
              {
                "id": "test-direction-test-tools-visual-automation-record-replay-and-system-design",
                "title": "行为录制回放与自动化系统化设计",
                "file": "content/test-direction/test-tools/visual-automation/record-replay-and-system-design.md"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "category": "技术基础",
    "sections": [
      {
        "id": "tech-base-python",
        "title": "Python",
        "file": "content/tech-base/python/index.md",
        "topics": [
          {
            "id": "tech-base-python-data-types",
            "title": "Python 数据类型",
            "file": "content/tech-base/python/data-types/index.md",
            "articles": [
              {
                "id": "tech-base-python-data-types-python-data-types-overview",
                "title": "Python 数据类型总览与区别",
                "file": "content/tech-base/python/data-types/python-data-types-overview.md"
              },
              {
                "id": "tech-base-python-data-types-mutable-immutable-and-copying",
                "title": "可变、不可变与拷贝语义",
                "file": "content/tech-base/python/data-types/mutable-immutable-and-copying.md"
              },
              {
                "id": "tech-base-python-data-types-python-data-types-cheatsheet",
                "title": "Python 数据类型常用操作",
                "file": "content/tech-base/python/data-types/python-data-types-cheatsheet.md"
              }
            ]
          },
          {
            "id": "tech-base-python-control-flow-and-functions",
            "title": "流程控制与函数",
            "file": "content/tech-base/python/control-flow-and-functions/index.md",
            "articles": [
              {
                "id": "tech-base-python-control-flow-and-functions-python-condition-loop",
                "title": "条件、循环与推导式",
                "file": "content/tech-base/python/control-flow-and-functions/python-condition-loop.md"
              },
              {
                "id": "tech-base-python-control-flow-and-functions-decorator-generator-and-iterator",
                "title": "装饰器、生成器与迭代器",
                "file": "content/tech-base/python/control-flow-and-functions/decorator-generator-and-iterator.md"
              },
              {
                "id": "tech-base-python-control-flow-and-functions-python-functions-and-scope",
                "title": "函数、作用域与参数传递",
                "file": "content/tech-base/python/control-flow-and-functions/python-functions-and-scope.md"
              }
            ]
          },
          {
            "id": "tech-base-python-file-and-standard-library",
            "title": "文件处理与常用标准库",
            "file": "content/tech-base/python/file-and-standard-library/index.md",
            "articles": [
              {
                "id": "tech-base-python-file-and-standard-library-python-file-json",
                "title": "文件、JSON 与脚本输入输出",
                "file": "content/tech-base/python/file-and-standard-library/python-file-json.md"
              },
              {
                "id": "tech-base-python-file-and-standard-library-python-csv-pathlib-subprocess-workflow",
                "title": "CSV、Pathlib 与 subprocess 组合流程",
                "file": "content/tech-base/python/file-and-standard-library/python-csv-pathlib-subprocess-workflow.md"
              },
              {
                "id": "tech-base-python-file-and-standard-library-python-common-standard-library",
                "title": "高频标准库怎么理解和选用",
                "file": "content/tech-base/python/file-and-standard-library/python-common-standard-library.md"
              }
            ]
          },
          {
            "id": "tech-base-python-exception-and-classes",
            "title": "异常处理与类",
            "file": "content/tech-base/python/exception-and-classes/index.md",
            "articles": [
              {
                "id": "tech-base-python-exception-and-classes-python-exception-handling",
                "title": "异常处理在解决什么问题",
                "file": "content/tech-base/python/exception-and-classes/python-exception-handling.md"
              },
              {
                "id": "tech-base-python-exception-and-classes-python-dataclass-and-object-model",
                "title": "dataclass 与对象建模",
                "file": "content/tech-base/python/exception-and-classes/python-dataclass-and-object-model.md"
              },
              {
                "id": "tech-base-python-exception-and-classes-python-context-manager-and-resource-cleanup",
                "title": "上下文管理器与资源清理",
                "file": "content/tech-base/python/exception-and-classes/python-context-manager-and-resource-cleanup.md"
              },
              {
                "id": "tech-base-python-exception-and-classes-python-custom-exception-and-boundary",
                "title": "自定义异常、边界转换与错误语义",
                "file": "content/tech-base/python/exception-and-classes/python-custom-exception-and-boundary.md"
              },
              {
                "id": "tech-base-python-exception-and-classes-python-class-and-object",
                "title": "类、对象与面向对象怎么理解",
                "file": "content/tech-base/python/exception-and-classes/python-class-and-object.md"
              }
            ]
          }
        ]
      },
      {
        "id": "tech-base-cpp",
        "title": "C++",
        "file": "content/tech-base/cpp/index.md",
        "topics": [
          {
            "id": "tech-base-cpp-basic-syntax",
            "title": "C++ 基础语法",
            "file": "content/tech-base/cpp/basic-syntax/index.md",
            "articles": [
              {
                "id": "tech-base-cpp-basic-syntax-const-copy-and-parameter-passing",
                "title": "const、拷贝与参数传递怎么选",
                "file": "content/tech-base/cpp/basic-syntax/const-copy-and-parameter-passing.md"
              },
              {
                "id": "tech-base-cpp-basic-syntax-lifetime-reference-and-dangling",
                "title": "生命周期、引用与悬垂问题",
                "file": "content/tech-base/cpp/basic-syntax/lifetime-reference-and-dangling.md"
              },
              {
                "id": "tech-base-cpp-basic-syntax-references-pointers-and-basics",
                "title": "引用、指针与基础语法",
                "file": "content/tech-base/cpp/basic-syntax/references-pointers-and-basics.md"
              }
            ]
          },
          {
            "id": "tech-base-cpp-object-model-and-memory",
            "title": "C++ 对象模型与内存",
            "file": "content/tech-base/cpp/object-model-and-memory/index.md",
            "articles": [
              {
                "id": "tech-base-cpp-object-model-and-memory-object-lifecycle",
                "title": "对象生命周期管理",
                "file": "content/tech-base/cpp/object-model-and-memory/object-lifecycle.md"
              },
              {
                "id": "tech-base-cpp-object-model-and-memory-memory-leak-and-troubleshooting",
                "title": "内存泄露 / 未释放及排查",
                "file": "content/tech-base/cpp/object-model-and-memory/memory-leak-and-troubleshooting.md"
              },
              {
                "id": "tech-base-cpp-object-model-and-memory-copy-move-and-resource",
                "title": "拷贝、移动与资源所有权",
                "file": "content/tech-base/cpp/object-model-and-memory/copy-move-and-resource.md"
              }
            ]
          },
          {
            "id": "tech-base-cpp-stl-and-high-frequency-syntax",
            "title": "C++ STL 与高频语法",
            "file": "content/tech-base/cpp/stl-and-high-frequency-syntax/index.md",
            "articles": [
              {
                "id": "tech-base-cpp-stl-and-high-frequency-syntax-templates-string-pair-lambda-priority-queue",
                "title": "C++ 模板补充手册：string、pair、lambda、比较器、自定义排序、priority_queue",
                "file": "content/tech-base/cpp/stl-and-high-frequency-syntax/templates-string-pair-lambda-priority-queue.md"
              },
              {
                "id": "tech-base-cpp-stl-and-high-frequency-syntax-iterator-invalidations-and-common-pitfalls",
                "title": "迭代器失效与常见 STL 陷阱",
                "file": "content/tech-base/cpp/stl-and-high-frequency-syntax/iterator-invalidations-and-common-pitfalls.md"
              },
              {
                "id": "tech-base-cpp-stl-and-high-frequency-syntax-stl-containers-iterators-algorithms",
                "title": "C++ STL 容器、迭代器与算法",
                "file": "content/tech-base/cpp/stl-and-high-frequency-syntax/stl-containers-iterators-algorithms.md"
              }
            ]
          }
        ]
      },
      {
        "id": "tech-base-dsa",
        "title": "数据结构与算法",
        "file": "content/tech-base/dsa/index.md",
        "topics": [
          {
            "id": "tech-base-dsa-container-comparison",
            "title": "容器专题",
            "file": "content/tech-base/dsa/container-comparison/index.md",
            "articles": [
              {
                "id": "tech-base-dsa-container-comparison-container-selection-by-access-pattern",
                "title": "按访问模式选择容器",
                "file": "content/tech-base/dsa/container-comparison/container-selection-by-access-pattern.md"
              },
              {
                "id": "tech-base-dsa-container-comparison-ordered-vs-unordered-structure-tradeoffs",
                "title": "有序与无序结构的取舍",
                "file": "content/tech-base/dsa/container-comparison/ordered-vs-unordered-structure-tradeoffs.md"
              },
              {
                "id": "tech-base-dsa-container-comparison-cpp-python-containers-comparison",
                "title": "C++ 容器与 Python 容器完整对照手册",
                "file": "content/tech-base/dsa/container-comparison/cpp-python-containers-comparison.md"
              }
            ]
          },
          {
            "id": "tech-base-dsa-linear-structures",
            "title": "线性结构与访问模式",
            "file": "content/tech-base/dsa/linear-structures/index.md",
            "articles": [
              {
                "id": "tech-base-dsa-linear-structures-array-list-stack-queue",
                "title": "数组、链表、栈与队列怎么区分",
                "file": "content/tech-base/dsa/linear-structures/array-list-stack-queue.md"
              },
              {
                "id": "tech-base-dsa-linear-structures-monotonic-structure-and-sliding-window",
                "title": "单调栈、单调队列与滑动窗口",
                "file": "content/tech-base/dsa/linear-structures/monotonic-structure-and-sliding-window.md"
              },
              {
                "id": "tech-base-dsa-linear-structures-deque-heap-priority",
                "title": "双端队列、堆与优先级结构",
                "file": "content/tech-base/dsa/linear-structures/deque-heap-priority.md"
              }
            ]
          },
          {
            "id": "tech-base-dsa-hash-and-tree",
            "title": "哈希、树与查找组织",
            "file": "content/tech-base/dsa/hash-and-tree/index.md",
            "articles": [
              {
                "id": "tech-base-dsa-hash-and-tree-hash-table-set-map",
                "title": "哈希表、集合和映射的核心思想",
                "file": "content/tech-base/dsa/hash-and-tree/hash-table-set-map.md"
              },
              {
                "id": "tech-base-dsa-hash-and-tree-trie-and-prefix-indexing",
                "title": "Trie 与前缀索引",
                "file": "content/tech-base/dsa/hash-and-tree/trie-and-prefix-indexing.md"
              },
              {
                "id": "tech-base-dsa-hash-and-tree-tree-bst-balance",
                "title": "树、二叉搜索树与平衡性的意义",
                "file": "content/tech-base/dsa/hash-and-tree/tree-bst-balance.md"
              }
            ]
          },
          {
            "id": "tech-base-dsa-algorithmic-thinking",
            "title": "算法思维与复杂度",
            "file": "content/tech-base/dsa/algorithmic-thinking/index.md",
            "articles": [
              {
                "id": "tech-base-dsa-algorithmic-thinking-time-space-complexity",
                "title": "时间复杂度与空间复杂度怎么理解",
                "file": "content/tech-base/dsa/algorithmic-thinking/time-space-complexity.md"
              },
              {
                "id": "tech-base-dsa-algorithmic-thinking-recursion-backtracking-and-state-space",
                "title": "递归、回溯与状态空间怎么理解",
                "file": "content/tech-base/dsa/algorithmic-thinking/recursion-backtracking-and-state-space.md"
              },
              {
                "id": "tech-base-dsa-algorithmic-thinking-common-problem-patterns",
                "title": "双指针、二分、递归与动态规划的分界",
                "file": "content/tech-base/dsa/algorithmic-thinking/common-problem-patterns.md"
              }
            ]
          }
        ]
      },
      {
        "id": "tech-base-database-sql",
        "title": "数据库与 SQL",
        "file": "content/tech-base/database-sql/index.md",
        "topics": [
          {
            "id": "tech-base-database-sql-query-foundations",
            "title": "SQL 查询基础",
            "file": "content/tech-base/database-sql/query-foundations/index.md",
            "articles": [
              {
                "id": "tech-base-database-sql-query-foundations-query-thinking-and-result-shaping",
                "title": "查询思路与结果整形",
                "file": "content/tech-base/database-sql/query-foundations/query-thinking-and-result-shaping.md"
              },
              {
                "id": "tech-base-database-sql-query-foundations-grouping-dedup-and-latest-record",
                "title": "分组、去重和最近一条记录怎么想",
                "file": "content/tech-base/database-sql/query-foundations/grouping-dedup-and-latest-record.md"
              },
              {
                "id": "tech-base-database-sql-query-foundations-join-order-and-result-cardinality",
                "title": "连接顺序与结果基数怎么判断",
                "file": "content/tech-base/database-sql/query-foundations/join-order-and-result-cardinality.md"
              }
            ]
          },
          {
            "id": "tech-base-database-sql-business-validation",
            "title": "业务校验与测试查询",
            "file": "content/tech-base/database-sql/business-validation/index.md",
            "articles": [
              {
                "id": "tech-base-database-sql-business-validation-business-key-reconciliation",
                "title": "按业务键做链路对账",
                "file": "content/tech-base/database-sql/business-validation/business-key-reconciliation.md"
              },
              {
                "id": "tech-base-database-sql-business-validation-data-check-sql-patterns",
                "title": "数据校验 SQL 模式",
                "file": "content/tech-base/database-sql/business-validation/data-check-sql-patterns.md"
              },
              {
                "id": "tech-base-database-sql-business-validation-cross-table-consistency-checks",
                "title": "跨表一致性校验思路",
                "file": "content/tech-base/database-sql/business-validation/cross-table-consistency-checks.md"
              }
            ]
          },
          {
            "id": "tech-base-database-sql-storage-and-modeling",
            "title": "数据库建模与基础概念",
            "file": "content/tech-base/database-sql/storage-and-modeling/index.md",
            "articles": [
              {
                "id": "tech-base-database-sql-storage-and-modeling-table-design-and-normalization",
                "title": "表设计与范式怎么理解",
                "file": "content/tech-base/database-sql/storage-and-modeling/table-design-and-normalization.md"
              },
              {
                "id": "tech-base-database-sql-storage-and-modeling-constraints-and-data-integrity",
                "title": "约束、完整性与脏数据防线",
                "file": "content/tech-base/database-sql/storage-and-modeling/constraints-and-data-integrity.md"
              },
              {
                "id": "tech-base-database-sql-storage-and-modeling-hotspot-data-and-sharding-smells",
                "title": "热点数据与分库分表前的坏味道",
                "file": "content/tech-base/database-sql/storage-and-modeling/hotspot-data-and-sharding-smells.md"
              }
            ]
          },
          {
            "id": "tech-base-database-sql-transactions-and-concurrency",
            "title": "事务与并发控制",
            "file": "content/tech-base/database-sql/transactions-and-concurrency/index.md",
            "articles": [
              {
                "id": "tech-base-database-sql-transactions-and-concurrency-isolation-levels-and-anomalies",
                "title": "隔离级别与并发异常",
                "file": "content/tech-base/database-sql/transactions-and-concurrency/isolation-levels-and-anomalies.md"
              },
              {
                "id": "tech-base-database-sql-transactions-and-concurrency-locks-mvcc-and-deadlocks",
                "title": "锁、MVCC 与死锁分析",
                "file": "content/tech-base/database-sql/transactions-and-concurrency/locks-mvcc-and-deadlocks.md"
              },
              {
                "id": "tech-base-database-sql-transactions-and-concurrency-long-transaction-and-lock-wait-diagnosis",
                "title": "长事务与锁等待排查",
                "file": "content/tech-base/database-sql/transactions-and-concurrency/long-transaction-and-lock-wait-diagnosis.md"
              }
            ]
          },
          {
            "id": "tech-base-database-sql-optimization-and-troubleshooting",
            "title": "索引、执行计划与性能排查",
            "file": "content/tech-base/database-sql/optimization-and-troubleshooting/index.md",
            "articles": [
              {
                "id": "tech-base-database-sql-optimization-and-troubleshooting-query-slowdown-diagnosis-path",
                "title": "查询变慢时如何建立排查路径",
                "file": "content/tech-base/database-sql/optimization-and-troubleshooting/query-slowdown-diagnosis-path.md"
              },
              {
                "id": "tech-base-database-sql-optimization-and-troubleshooting-index-miss-and-scan-expansion",
                "title": "索引失效与扫描范围膨胀怎么判断",
                "file": "content/tech-base/database-sql/optimization-and-troubleshooting/index-miss-and-scan-expansion.md"
              },
              {
                "id": "tech-base-database-sql-optimization-and-troubleshooting-sort-group-temporary-table-cost",
                "title": "排序、分组与临时表成本",
                "file": "content/tech-base/database-sql/optimization-and-troubleshooting/sort-group-temporary-table-cost.md"
              }
            ]
          },
          {
            "id": "tech-base-database-sql-interview-and-expression",
            "title": "高频题与知识串联",
            "file": "content/tech-base/database-sql/interview-and-expression/index.md",
            "articles": [
              {
                "id": "tech-base-database-sql-interview-and-expression-database-concepts-answering-framework",
                "title": "数据库概念题如何组织回答",
                "file": "content/tech-base/database-sql/interview-and-expression/database-concepts-answering-framework.md"
              },
              {
                "id": "tech-base-database-sql-interview-and-expression-database-problem-diagnosis-answering",
                "title": "数据库问题排查题怎么答",
                "file": "content/tech-base/database-sql/interview-and-expression/database-problem-diagnosis-answering.md"
              },
              {
                "id": "tech-base-database-sql-interview-and-expression-sql-optimization-answering-and-tradeoff",
                "title": "优化题怎么回答才不显得只会说加索引",
                "file": "content/tech-base/database-sql/interview-and-expression/sql-optimization-answering-and-tradeoff.md"
              }
            ]
          },
          {
            "id": "tech-base-database-sql-database-principles",
            "title": "数据库原理",
            "file": "content/tech-base/database-sql/database-principles/index.md",
            "articles": [
              {
                "id": "tech-base-database-sql-database-principles-database-fundamentals",
                "title": "05 数据库基础概念",
                "file": "content/tech-base/database-sql/database-principles/database-fundamentals.md"
              },
              {
                "id": "tech-base-database-sql-database-principles-storage-engine-and-index-organization",
                "title": "存储引擎与索引组织方式",
                "file": "content/tech-base/database-sql/database-principles/storage-engine-and-index-organization.md"
              },
              {
                "id": "tech-base-database-sql-database-principles-transactions-and-concurrency-control",
                "title": "06 事务与并发控制",
                "file": "content/tech-base/database-sql/database-principles/transactions-and-concurrency-control.md"
              }
            ]
          },
          {
            "id": "tech-base-database-sql-interview-faq",
            "title": "数据库与 SQL 高频题",
            "file": "content/tech-base/database-sql/interview-faq/index.md",
            "articles": [
              {
                "id": "tech-base-database-sql-interview-faq-database-and-sql-interview-faq",
                "title": "数据库与 SQL 高频问题串联",
                "file": "content/tech-base/database-sql/interview-faq/database-and-sql-interview-faq.md"
              },
              {
                "id": "tech-base-database-sql-interview-faq-database-transaction-lock-faq",
                "title": "事务、锁与并发高频题",
                "file": "content/tech-base/database-sql/interview-faq/database-transaction-lock-faq.md"
              },
              {
                "id": "tech-base-database-sql-interview-faq-sql-and-index-misconceptions",
                "title": "最容易混淆的数据库高频概念",
                "file": "content/tech-base/database-sql/interview-faq/sql-and-index-misconceptions.md"
              }
            ]
          },
          {
            "id": "tech-base-database-sql-performance-and-troubleshooting",
            "title": "性能优化与排查",
            "file": "content/tech-base/database-sql/performance-and-troubleshooting/index.md",
            "articles": [
              {
                "id": "tech-base-database-sql-performance-and-troubleshooting-deep-pagination-covering-index-and-back-to-table",
                "title": "深分页、回表与覆盖索引为什么会慢",
                "file": "content/tech-base/database-sql/performance-and-troubleshooting/deep-pagination-covering-index-and-back-to-table.md"
              },
              {
                "id": "tech-base-database-sql-performance-and-troubleshooting-indexes-and-execution-plans",
                "title": "07 索引与执行计划",
                "file": "content/tech-base/database-sql/performance-and-troubleshooting/indexes-and-execution-plans.md"
              },
              {
                "id": "tech-base-database-sql-performance-and-troubleshooting-slow-queries-and-troubleshooting",
                "title": "08 慢查询与排查基础",
                "file": "content/tech-base/database-sql/performance-and-troubleshooting/slow-queries-and-troubleshooting.md"
              }
            ]
          },
          {
            "id": "tech-base-database-sql-sql-basics",
            "title": "SQL 基础与查询",
            "file": "content/tech-base/database-sql/sql-basics/index.md",
            "articles": [
              {
                "id": "tech-base-database-sql-sql-basics-joins-and-subqueries",
                "title": "02 SQL 连接与子查询",
                "file": "content/tech-base/database-sql/sql-basics/joins-and-subqueries.md"
              },
              {
                "id": "tech-base-database-sql-sql-basics-sql-basics",
                "title": "01 SQL 基础语法",
                "file": "content/tech-base/database-sql/sql-basics/sql-basics.md"
              },
              {
                "id": "tech-base-database-sql-sql-basics-sql-scenario-problems",
                "title": "04 测试场景 SQL",
                "file": "content/tech-base/database-sql/sql-basics/sql-scenario-problems.md"
              },
              {
                "id": "tech-base-database-sql-sql-basics-window-functions-and-faq",
                "title": "03 SQL 窗口函数与高频题",
                "file": "content/tech-base/database-sql/sql-basics/window-functions-and-faq.md"
              }
            ]
          }
        ]
      },
      {
        "id": "tech-base-linux",
        "title": "Linux",
        "file": "content/tech-base/linux/index.md",
        "topics": [
          {
            "id": "tech-base-linux-common-commands",
            "title": "常用命令与文件操作",
            "file": "content/tech-base/linux/common-commands/index.md",
            "articles": [
              {
                "id": "tech-base-linux-common-commands-linux-files-and-search",
                "title": "文件、目录与搜索命令",
                "file": "content/tech-base/linux/common-commands/linux-files-and-search.md"
              },
              {
                "id": "tech-base-linux-common-commands-linux-pipeline-and-redirection",
                "title": "管道、重定向与命令组合",
                "file": "content/tech-base/linux/common-commands/linux-pipeline-and-redirection.md"
              },
              {
                "id": "tech-base-linux-common-commands-linux-text-processing",
                "title": "文本查看与处理命令",
                "file": "content/tech-base/linux/common-commands/linux-text-processing.md"
              }
            ]
          },
          {
            "id": "tech-base-linux-process-and-service",
            "title": "进程与服务管理",
            "file": "content/tech-base/linux/process-and-service/index.md",
            "articles": [
              {
                "id": "tech-base-linux-process-and-service-linux-process-observation",
                "title": "进程观察与资源查看",
                "file": "content/tech-base/linux/process-and-service/linux-process-observation.md"
              },
              {
                "id": "tech-base-linux-process-and-service-signal-exit-code-and-process-control",
                "title": "信号、退出码与进程控制",
                "file": "content/tech-base/linux/process-and-service/signal-exit-code-and-process-control.md"
              },
              {
                "id": "tech-base-linux-process-and-service-linux-service-control",
                "title": "服务管理与启动项排查",
                "file": "content/tech-base/linux/process-and-service/linux-service-control.md"
              }
            ]
          },
          {
            "id": "tech-base-linux-network-and-port",
            "title": "网络与端口排查",
            "file": "content/tech-base/linux/network-and-port/index.md",
            "articles": [
              {
                "id": "tech-base-linux-network-and-port-linux-network-check",
                "title": "网络连通性与端口检查",
                "file": "content/tech-base/linux/network-and-port/linux-network-check.md"
              },
              {
                "id": "tech-base-linux-network-and-port-linux-curl-ss-tcpdump-workflow",
                "title": "curl、ss、tcpdump 组合排查路径",
                "file": "content/tech-base/linux/network-and-port/linux-curl-ss-tcpdump-workflow.md"
              },
              {
                "id": "tech-base-linux-network-and-port-linux-connection-location",
                "title": "连接异常如何定位到进程与服务",
                "file": "content/tech-base/linux/network-and-port/linux-connection-location.md"
              }
            ]
          },
          {
            "id": "tech-base-linux-logging-and-troubleshooting",
            "title": "日志与排障路径",
            "file": "content/tech-base/linux/logging-and-troubleshooting/index.md",
            "articles": [
              {
                "id": "tech-base-linux-logging-and-troubleshooting-linux-log-reading",
                "title": "日志查看与关键线索提取",
                "file": "content/tech-base/linux/logging-and-troubleshooting/linux-log-reading.md"
              },
              {
                "id": "tech-base-linux-logging-and-troubleshooting-journalctl-dmesg-and-kernel-signals",
                "title": "journalctl、dmesg 与内核信号",
                "file": "content/tech-base/linux/logging-and-troubleshooting/journalctl-dmesg-and-kernel-signals.md"
              },
              {
                "id": "tech-base-linux-logging-and-troubleshooting-linux-troubleshooting-flow",
                "title": "Linux 排障的一般路径",
                "file": "content/tech-base/linux/logging-and-troubleshooting/linux-troubleshooting-flow.md"
              }
            ]
          }
        ]
      },
      {
        "id": "tech-base-network",
        "title": "计算机网络",
        "file": "content/tech-base/network/index.md",
        "topics": [
          {
            "id": "tech-base-network-transport-and-connections",
            "title": "传输层与连接语义",
            "file": "content/tech-base/network/transport-and-connections/index.md",
            "articles": [
              {
                "id": "tech-base-network-transport-and-connections-tcp-udp-core-differences",
                "title": "TCP 与 UDP 的核心区别",
                "file": "content/tech-base/network/transport-and-connections/tcp-udp-core-differences.md"
              },
              {
                "id": "tech-base-network-transport-and-connections-tcp-flow-and-congestion-control",
                "title": "TCP 流量控制与拥塞控制",
                "file": "content/tech-base/network/transport-and-connections/tcp-flow-and-congestion-control.md"
              },
              {
                "id": "tech-base-network-transport-and-connections-tcp-handshake-and-reliability",
                "title": "TCP 三次握手、四次挥手与可靠性",
                "file": "content/tech-base/network/transport-and-connections/tcp-handshake-and-reliability.md"
              }
            ]
          },
          {
            "id": "tech-base-network-http-and-dns",
            "title": "HTTP、HTTPS 与 DNS",
            "file": "content/tech-base/network/http-and-dns/index.md",
            "articles": [
              {
                "id": "tech-base-network-http-and-dns-url-to-page-rendering",
                "title": "从输入 URL 到页面显示",
                "file": "content/tech-base/network/http-and-dns/url-to-page-rendering.md"
              },
              {
                "id": "tech-base-network-http-and-dns-http-cache-cors-and-preflight",
                "title": "缓存、CORS 与预检请求",
                "file": "content/tech-base/network/http-and-dns/http-cache-cors-and-preflight.md"
              },
              {
                "id": "tech-base-network-http-and-dns-cookie-session-token",
                "title": "Cookie、Session 与 Token 怎么区分",
                "file": "content/tech-base/network/http-and-dns/cookie-session-token.md"
              }
            ]
          },
          {
            "id": "tech-base-network-performance-and-troubleshooting",
            "title": "网络故障与性能定位",
            "file": "content/tech-base/network/performance-and-troubleshooting/index.md",
            "articles": [
              {
                "id": "tech-base-network-performance-and-troubleshooting-network-latency-timeout-retry",
                "title": "延迟、超时与重试怎么串起来看",
                "file": "content/tech-base/network/performance-and-troubleshooting/network-latency-timeout-retry.md"
              },
              {
                "id": "tech-base-network-performance-and-troubleshooting-connection-pool-keepalive-and-half-open",
                "title": "连接池、Keep-Alive 与半开连接",
                "file": "content/tech-base/network/performance-and-troubleshooting/connection-pool-keepalive-and-half-open.md"
              },
              {
                "id": "tech-base-network-performance-and-troubleshooting-dns-tls-proxy-layer-location",
                "title": "DNS、TLS 与代理层怎么分层定位",
                "file": "content/tech-base/network/performance-and-troubleshooting/dns-tls-proxy-layer-location.md"
              },
              {
                "id": "tech-base-network-performance-and-troubleshooting-network-problem-location",
                "title": "网络问题如何按层定位",
                "file": "content/tech-base/network/performance-and-troubleshooting/network-problem-location.md"
              },
              {
                "id": "tech-base-network-performance-and-troubleshooting-retry-storm-and-backoff",
                "title": "重试风暴与退避策略",
                "file": "content/tech-base/network/performance-and-troubleshooting/retry-storm-and-backoff.md"
              }
            ]
          }
        ]
      },
      {
        "id": "tech-base-os",
        "title": "操作系统",
        "file": "content/tech-base/os/index.md",
        "topics": [
          {
            "id": "tech-base-os-concurrency-and-scheduling",
            "title": "并发与调度",
            "file": "content/tech-base/os/concurrency-and-scheduling/index.md",
            "articles": [
              {
                "id": "tech-base-os-concurrency-and-scheduling-thread-safety-and-synchronization",
                "title": "线程安全与同步原语怎么取舍",
                "file": "content/tech-base/os/concurrency-and-scheduling/thread-safety-and-synchronization.md"
              },
              {
                "id": "tech-base-os-concurrency-and-scheduling-deadlock-livelock-and-starvation",
                "title": "死锁、活锁与饥饿怎么区分",
                "file": "content/tech-base/os/concurrency-and-scheduling/deadlock-livelock-and-starvation.md"
              },
              {
                "id": "tech-base-os-concurrency-and-scheduling-core-concepts",
                "title": "并发、并行、同步、异步、阻塞、非阻塞",
                "file": "content/tech-base/os/concurrency-and-scheduling/core-concepts.md"
              }
            ]
          },
          {
            "id": "tech-base-os-memory-and-process-management",
            "title": "内存与进程管理",
            "file": "content/tech-base/os/memory-and-process-management/index.md",
            "articles": [
              {
                "id": "tech-base-os-memory-and-process-management-memory-virtual-and-physical",
                "title": "虚拟内存、物理内存与分页怎么理解",
                "file": "content/tech-base/os/memory-and-process-management/memory-virtual-and-physical.md"
              },
              {
                "id": "tech-base-os-memory-and-process-management-memory-leak-oom-and-core-dump",
                "title": "内存泄漏、OOM 与 core dump",
                "file": "content/tech-base/os/memory-and-process-management/memory-leak-oom-and-core-dump.md"
              },
              {
                "id": "tech-base-os-memory-and-process-management-process-state-and-context-switch",
                "title": "进程状态与上下文切换在解决什么",
                "file": "content/tech-base/os/memory-and-process-management/process-state-and-context-switch.md"
              }
            ]
          },
          {
            "id": "tech-base-os-process-thread-and-communication",
            "title": "进程、线程与通信",
            "file": "content/tech-base/os/process-thread-and-communication/index.md",
            "articles": [
              {
                "id": "tech-base-os-process-thread-and-communication-ipc-selection-and-scenario",
                "title": "进程间通信该怎么选",
                "file": "content/tech-base/os/process-thread-and-communication/ipc-selection-and-scenario.md"
              },
              {
                "id": "tech-base-os-process-thread-and-communication-thread-pool-and-context-switch-cost",
                "title": "线程池与上下文切换成本",
                "file": "content/tech-base/os/process-thread-and-communication/thread-pool-and-context-switch-cost.md"
              },
              {
                "id": "tech-base-os-process-thread-and-communication-process-thread-communication-and-scheduling",
                "title": "进程、线程与通信机制",
                "file": "content/tech-base/os/process-thread-and-communication/process-thread-communication-and-scheduling.md"
              }
            ]
          },
          {
            "id": "tech-base-os-file-system-and-io",
            "title": "文件系统与 IO",
            "file": "content/tech-base/os/file-system-and-io/index.md",
            "articles": [
              {
                "id": "tech-base-os-file-system-and-io-file-system-core-concepts",
                "title": "文件系统在解决什么问题",
                "file": "content/tech-base/os/file-system-and-io/file-system-core-concepts.md"
              },
              {
                "id": "tech-base-os-file-system-and-io-disk-io-page-cache-and-writeback",
                "title": "磁盘 IO、页缓存与回写机制",
                "file": "content/tech-base/os/file-system-and-io/disk-io-page-cache-and-writeback.md"
              },
              {
                "id": "tech-base-os-file-system-and-io-inode-fd-and-open-file-table",
                "title": "inode、文件描述符与打开文件表",
                "file": "content/tech-base/os/file-system-and-io/inode-fd-and-open-file-table.md"
              },
              {
                "id": "tech-base-os-file-system-and-io-mmap-vs-read-write-and-page-fault",
                "title": "mmap、普通读写与缺页异常",
                "file": "content/tech-base/os/file-system-and-io/mmap-vs-read-write-and-page-fault.md"
              },
              {
                "id": "tech-base-os-file-system-and-io-io-blocking-and-multiplexing",
                "title": "阻塞 IO、非阻塞 IO 与多路复用",
                "file": "content/tech-base/os/file-system-and-io/io-blocking-and-multiplexing.md"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "category": "代码题目",
    "sections": [
      {
        "id": "code-problems-code-reading",
        "title": "代码阅读",
        "file": "content/code-problems/code-reading/index.md",
        "topics": [
          {
            "id": "code-problems-code-reading-reading-strategy",
            "title": "阅读路径与状态跟踪",
            "file": "content/code-problems/code-reading/reading-strategy/index.md",
            "articles": [
              {
                "id": "code-problems-code-reading-reading-strategy-code-reading-entry-points",
                "title": "代码阅读从哪里开始",
                "file": "content/code-problems/code-reading/reading-strategy/code-reading-entry-points.md"
              },
              {
                "id": "code-problems-code-reading-reading-strategy-code-reading-state-and-flow",
                "title": "如何追踪状态变化与调用链",
                "file": "content/code-problems/code-reading/reading-strategy/code-reading-state-and-flow.md"
              }
            ]
          }
        ]
      },
      {
        "id": "code-problems-bug-location",
        "title": "Bug 定位",
        "file": "content/code-problems/bug-location/index.md",
        "topics": [
          {
            "id": "code-problems-bug-location-location-strategy",
            "title": "定位路径与证据组织",
            "file": "content/code-problems/bug-location/location-strategy/index.md",
            "articles": [
              {
                "id": "code-problems-bug-location-location-strategy-bug-location-from-symptom",
                "title": "从现象反推模块与链路",
                "file": "content/code-problems/bug-location/location-strategy/bug-location-from-symptom.md"
              },
              {
                "id": "code-problems-bug-location-location-strategy-bug-location-logs-and-breakpoints",
                "title": "日志、断点与对比实验怎么配合",
                "file": "content/code-problems/bug-location/location-strategy/bug-location-logs-and-breakpoints.md"
              }
            ]
          }
        ]
      },
      {
        "id": "code-problems-sql-problems",
        "title": "SQL 题",
        "file": "content/code-problems/sql-problems/index.md",
        "topics": [
          {
            "id": "code-problems-sql-problems-query-patterns",
            "title": "查询题型与拆解方法",
            "file": "content/code-problems/sql-problems/query-patterns/index.md",
            "articles": [
              {
                "id": "code-problems-sql-problems-query-patterns-sql-grouping-patterns",
                "title": "分组统计类 SQL 怎么拆",
                "file": "content/code-problems/sql-problems/query-patterns/sql-grouping-patterns.md"
              },
              {
                "id": "code-problems-sql-problems-query-patterns-sql-join-and-window-patterns",
                "title": "连接、窗口函数与去重题型",
                "file": "content/code-problems/sql-problems/query-patterns/sql-join-and-window-patterns.md"
              }
            ]
          }
        ]
      },
      {
        "id": "code-problems-cpp-problems",
        "title": "C++ 题",
        "file": "content/code-problems/cpp-problems/index.md",
        "topics": [
          {
            "id": "code-problems-cpp-problems-object-and-stl",
            "title": "对象与 STL",
            "file": "content/code-problems/cpp-problems/object-and-stl/index.md",
            "articles": [
              {
                "id": "code-problems-cpp-problems-object-and-stl-cpp-object-semantics-problems",
                "title": "对象语义题怎么判断",
                "file": "content/code-problems/cpp-problems/object-and-stl/cpp-object-semantics-problems.md"
              },
              {
                "id": "code-problems-cpp-problems-object-and-stl-cpp-stl-selection-problems",
                "title": "STL 选型与复杂度题怎么想",
                "file": "content/code-problems/cpp-problems/object-and-stl/cpp-stl-selection-problems.md"
              }
            ]
          }
        ]
      },
      {
        "id": "code-problems-python-problems",
        "title": "Python 题",
        "file": "content/code-problems/python-problems/index.md",
        "topics": [
          {
            "id": "code-problems-python-problems-data-and-scripting",
            "title": "数据结构与脚本处理",
            "file": "content/code-problems/python-problems/data-and-scripting/index.md",
            "articles": [
              {
                "id": "code-problems-python-problems-data-and-scripting-python-data-structure-problems",
                "title": "Python 数据结构题怎么拆",
                "file": "content/code-problems/python-problems/data-and-scripting/python-data-structure-problems.md"
              },
              {
                "id": "code-problems-python-problems-data-and-scripting-python-script-processing-problems",
                "title": "文本处理与脚本题怎么组织",
                "file": "content/code-problems/python-problems/data-and-scripting/python-script-processing-problems.md"
              }
            ]
          }
        ]
      },
      {
        "id": "code-problems-scenario-problems",
        "title": "场景设计题",
        "file": "content/code-problems/scenario-problems/index.md",
        "topics": [
          {
            "id": "code-problems-scenario-problems-test-and-automation",
            "title": "测试设计与自动化系统",
            "file": "content/code-problems/scenario-problems/test-and-automation/index.md",
            "articles": [
              {
                "id": "code-problems-scenario-problems-test-and-automation-scenario-test-design",
                "title": "场景题里的测试设计怎么展开",
                "file": "content/code-problems/scenario-problems/test-and-automation/scenario-test-design.md"
              },
              {
                "id": "code-problems-scenario-problems-test-and-automation-scenario-automation-architecture",
                "title": "自动化系统题怎么搭框架",
                "file": "content/code-problems/scenario-problems/test-and-automation/scenario-automation-architecture.md"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "category": "面试题目",
    "sections": [
      {
        "id": "interviews-qa-interview",
        "title": "测试岗面试题",
        "file": "content/interviews/qa-interview/index.md",
        "topics": [
          {
            "id": "interviews-qa-interview-testing-core",
            "title": "测试核心能力",
            "file": "content/interviews/qa-interview/testing-core/index.md",
            "articles": [
              {
                "id": "interviews-qa-interview-testing-core-qa-interview-testing-thinking",
                "title": "测试思维与质量理解怎么讲",
                "file": "content/interviews/qa-interview/testing-core/qa-interview-testing-thinking.md"
              },
              {
                "id": "interviews-qa-interview-testing-core-qa-interview-case-and-defect",
                "title": "用例设计与缺陷管理怎么讲",
                "file": "content/interviews/qa-interview/testing-core/qa-interview-case-and-defect.md"
              }
            ]
          }
        ]
      },
      {
        "id": "interviews-tech-interview",
        "title": "技术基础面试题",
        "file": "content/interviews/tech-interview/index.md",
        "topics": [
          {
            "id": "interviews-tech-interview-system-foundations",
            "title": "系统基础与排查表达",
            "file": "content/interviews/tech-interview/system-foundations/index.md",
            "articles": [
              {
                "id": "interviews-tech-interview-system-foundations-tech-interview-network-os",
                "title": "网络与操作系统问题怎么答",
                "file": "content/interviews/tech-interview/system-foundations/tech-interview-network-os.md"
              },
              {
                "id": "interviews-tech-interview-system-foundations-tech-interview-db-and-language",
                "title": "数据库与语言基础怎么答",
                "file": "content/interviews/tech-interview/system-foundations/tech-interview-db-and-language.md"
              }
            ]
          }
        ]
      },
      {
        "id": "interviews-game-qa-interview",
        "title": "游戏测试面试题",
        "file": "content/interviews/game-qa-interview/index.md",
        "topics": [
          {
            "id": "interviews-game-qa-interview-game-testing-special",
            "title": "专项能力与定位方法",
            "file": "content/interviews/game-qa-interview/game-testing-special/index.md",
            "articles": [
              {
                "id": "interviews-game-qa-interview-game-testing-special-game-qa-interview-special-tests",
                "title": "游戏专项测试怎么展开",
                "file": "content/interviews/game-qa-interview/game-testing-special/game-qa-interview-special-tests.md"
              },
              {
                "id": "interviews-game-qa-interview-game-testing-special-game-qa-interview-problem-location",
                "title": "游戏问题定位怎么讲",
                "file": "content/interviews/game-qa-interview/game-testing-special/game-qa-interview-problem-location.md"
              }
            ]
          }
        ]
      },
      {
        "id": "interviews-project-interview",
        "title": "项目经历题",
        "file": "content/interviews/project-interview/index.md",
        "topics": [
          {
            "id": "interviews-project-interview-project-story",
            "title": "项目梳理与亮点表达",
            "file": "content/interviews/project-interview/project-story/index.md",
            "articles": [
              {
                "id": "interviews-project-interview-project-story-project-interview-structure",
                "title": "项目经历如何讲成完整故事",
                "file": "content/interviews/project-interview/project-story/project-interview-structure.md"
              },
              {
                "id": "interviews-project-interview-project-story-project-interview-highlights",
                "title": "项目难点、决策与亮点怎么讲",
                "file": "content/interviews/project-interview/project-story/project-interview-highlights.md"
              }
            ]
          }
        ]
      },
      {
        "id": "interviews-intro-and-question",
        "title": "自我介绍与反问",
        "file": "content/interviews/intro-and-question/index.md",
        "topics": [
          {
            "id": "interviews-intro-and-question-introduction-and-questions",
            "title": "自我介绍与反问设计",
            "file": "content/interviews/intro-and-question/introduction-and-questions/index.md",
            "articles": [
              {
                "id": "interviews-intro-and-question-introduction-and-questions-self-introduction-structure",
                "title": "自我介绍怎么组织结构",
                "file": "content/interviews/intro-and-question/introduction-and-questions/self-introduction-structure.md"
              },
              {
                "id": "interviews-intro-and-question-introduction-and-questions-questions-for-interviewer",
                "title": "反问面试官时问什么更有效",
                "file": "content/interviews/intro-and-question/introduction-and-questions/questions-for-interviewer.md"
              }
            ]
          }
        ]
      }
    ]
  }
];

window.reviewData = reviewData;
