const fs = require("fs");
const path = require("path");
const { createContext } = require("./content-tree");

const context = createContext(path.resolve(__dirname, ".."));

function buildOutput(reviewData) {
  return `// This file is generated by scripts/generate-data.js.\n// Do not edit it manually. Edit content.config.js or the Markdown files instead.\n\nconst reviewData = ${JSON.stringify(reviewData, null, 2)};\n\nwindow.reviewData = reviewData;\n`;
}

function main() {
  const outputPath = path.join(context.projectRoot, "data.js");
  const reviewData = context.buildReviewData();
  fs.writeFileSync(outputPath, buildOutput(reviewData));
  console.log(`Generated data.js with ${reviewData.length} categories.`);
}

main();
